### ISSUE TITLE
close button

### ISSUE THREAD

**Issue by cornernote** [minetest-technic/unified_inventory#36]
Can we have a "close" button?  It's really handy for those who play on android.

**Comment by VanessaE** [comment]
I'd have to say it is more the job of the client, not the mod, to add appropriate widgets/decorations to the formspec, especially if the problem only occurs on certain platforms.

**Comment by cornernote** [comment]
It's not just an issue for the platform, it's also a UX improvement for all platforms.

Why would you not want a close button?

**Comment by VanessaE** [comment]
Because this mod mainly targets PC's, where you generally have an ESC key.  Although I made the "lite" mode for mobile devices, you usually have a "back" button on those platforms, which any reasonable person will assume backs out of the thing (formspec) that was just opened.  If that button isn't properly being mapped to "close formspec", that's an engine or OS problem, not a fault in UI.

**Comment by HybridDog** [comment]
l can't test it because it crashes when l try to start it on my device. Can you alternatively double tap outside the formspec to close it on android?

**Comment by VanessaE** [comment]
I believe there is a feature like that already in Minetest engine.  Don't recall if it's one or two taps, though.
