### ISSUE TITLE
Crafting guide uses textures from default mod

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-technic/unified_inventory#67]
The crafting guide depends on some textures from the `default` mod, namely for the crafting result (digging, smelting, etc.).
This means those icons will be missing if the `default` mod is missing.
Strictly spoken, this makes Unified Invetory hard-depend on `default` but actually adding this dependency would be really dumb IMO.

I suggest that Unified Inventory just provides its own icons here.

Any suggestions for good icons? If not, we could just copy the `default` textures and rename them.

**Comment by VanessaE** [comment]
UI hard-depends on default now.  There's no legit reason not to, imho.

**Comment by Wuzzy2** [comment]
Wait, what? NO! Please … :-(
A *hard* dependency on `default` only because of a 1-2 missing textures? This is crazy. Let's just add the missing textures and get rid of the dependency once and for all. Either by custom textures or by just copying the Minetest Game textures.

Unified Inventory works very well for subgames other than Minetest Game since many subgames also have a 8×4 inventory size and a 3×3 crafting grid. This is not because of Minetest Game, but because this is the Minetest default. So, Unified Inventory already works *almost* out of the box for most subgames, killing this compability is not good. :-(
It is not possible to use the dependency system to determine if the mod is perfectly suitable, so this mod should be rather advertised as “works with any subgame with a 8×4 player inventory and a 3×3 crafting grid” or something like that. ;-)

**Comment by VanessaE** [comment]
Unified Inventory was never meant to be used with anything other than minetest_game or a subgame based on it, and as far as I can tell, that covers 99% of Minetest users anyway.  Besides, are you sure the engine sets a default formspec?  Because, from all I can see, the subgame is what does that via `set_inventory_formspec`.

Anyway, it's a standing rule that you should directly reference textures in minetest_game instead of duplicating them.  This is part of what the dependency system was meant for, unless you need to alter the texture in some way that can't be done with texture modifiers, of course.

**Comment by Wuzzy2** [comment]
> are you sure

Yes, I am 100% sure about this. Tested with an empty subgame.

> Anyway, it's a standing rule that you should directly reference textures in minetest_game instead of duplicating them.

Well, this was only the “lazy” solution in order to have *some* icon available for all subgames. I have nothing against adding nice custom textures, however. If you wish, I can try to find you some. :-)

But if prime compability with other subgames is not seriously considered, or if the default dependency is now here to stay, I might consider forking Unified Inventory one day.
